config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'
  resources :memberships
  resources :beer_clubs
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :users
  resources :users do
    post 'toggle_closed', on: :member
  end
  get 'signup', to: 'users#new'
  root 'breweries#index'
  resources :beers
  get 'beerlist', to: 'beers#list'
  resources :breweries
  get 'brewerylist', to: 'breweries#list'
  resources :breweries do
    post 'toggle_activity', on: :member
  end
#  get 'ratings', to: 'ratings#index'
#  get 'ratings/new', to:'ratings#new'
#  post 'ratings', to: 'ratings#create'
  resources :ratings, only: [:index, :new, :create, :destroy]
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :membership
  has_many :users, dependent: :destroy, through: :membership
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :user_is_admin, only: [:destroy]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
            when "name" then @beer_clubs.sort_by(&:name)
            when "founded" then @beer_clubs.sort_by { |b| b.founded }
            when "city" then @beer_clubs.sort_by { |b| b.city }
            end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @membership.user = current_user

    current_membership = user_already_in_club
    if current_membership
      @current_membership = current_membership.id
      @user_already_in_club = true
    else
      @current_membership = 99
      @user_already_in_club = false
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  def user_already_in_club
    user_id = current_user.id
    beer_club_members = Membership.where beer_club_id: @beer_club.id
    beer_club_members.find_by user_id:
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <p>
    <strong>Name:</strong>
    <%= beer_club.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

  <p>
    <strong>Members:</strong>
    <% beer_club.users.each do |user| %>
      <%= link_to user.username, user %>
    <% end %>
  </p>

</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control" name="beer_club[name]">
  </div>

  <div>
    <label for="name" class="form-label">Founded</label>
    <input type="number" class="form-control" name="beer_club[founded]">
  </div>

  <div>
    <label for="name" class="form-label">City</label>
    <input type="text" class="form-control" name="beer_club[city]">
  </div>

  <div>
    <%= form.submit "Create beer club", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beer_clubs">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th><%= link_to "Name", beer_clubs_path(order: "name")%></th>
        <th><%= link_to "Founded", beer_clubs_path(order: "founded")%></th>
        <th><%= link_to "City", beer_clubs_path(order: "city")%></th>
      </tr>
    </thead>
    <tbody>
      <% @beer_clubs.each do |beer_club| %>
        <tr>
          <td> <%= link_to beer_club.name, beer_club %> </td>
          <td> <%= link_to beer_club.founded, beer_club %> </td>
          <td> <%= link_to beer_club.city, beer_club %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New beer club", new_beer_club_path if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<div><%= link_to "Back to beer clubs", beer_clubs_path %></div>

<% if current_user and not @user_already_in_club %>
<h4>Join a club:</h4>

  <%= form_with(model: @membership) do |form| %>
    <%= form.hidden_field :user_id %>
    <%= form.hidden_field :beer_club_id %>
    <%= form.submit "Join Club", class:"btn btn-primary" %>
  <% end %>
<% end %>

<% if current_user and @user_already_in_club %>
<h4>Leave this club</h4>

  <%= form_with(model: @membership, url: membership_path(@current_membership), method: :delete) do |form| %>
    <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit "End the membership", class:"btn btn-danger" %>
  <% end %>
<% end %>

<% if current_user %>
  <div>
    <%= link_to "Edit this beer club", edit_beer_club_path(@beer_club) %> |
    <%= button_to "Destroy this beer club", @beer_club, method: :delete %>
  </div>
<% end %>