config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'
  resources :memberships
  resources :beer_clubs
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :users
  resources :users do
    post 'toggle_closed', on: :member
  end
  get 'signup', to: 'users#new'
  root 'breweries#index'
  resources :beers
  get 'beerlist', to: 'beers#list'
  resources :breweries
  get 'brewerylist', to: 'breweries#list'
  resources :breweries do
    post 'toggle_activity', on: :member
  end
#  get 'ratings', to: 'ratings#index'
#  get 'ratings/new', to:'ratings#new'
#  post 'ratings', to: 'ratings#create'
  resources :ratings, only: [:index, :new, :create, :destroy]
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage
  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :year, numericality: {
    greater_than_or_equal_to: 1040,
    only_integer: true
  }

  validates :name, presence: true

  validate :year_cant_be_in_future,
           def year_cant_be_in_future
             return unless year.present? && year > Time.now.year

             errors.add(:year, "Year can't be in the future")
           end

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def ratings?
    !ratings.empty?
  end

  def self.top(amount)
    Brewery.order(average_rating: :desc).limit(amount)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :user_is_admin, only: [:destroy]
  
  # GET /breweries or /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  def list
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    expire_fragment('brewerylist')
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    expire_fragment('brewerylist')
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    expire_fragment('brewerylist')
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<% cache @brewery do %>
  <div id="<%= dom_id brewery %>">
    <h2>
      <strong>Name:</strong>
      <%= brewery.name %>
    </h2>

    <p>
      <strong>Year:</strong>
      <i> <%= "Established in #{brewery.year}" %></i>
    </p>

    <p>Beers count: <%= @brewery.beers.count %></p>

    <table class="table table-hover table-striped">
      <thead>
        <th>Name</th><th>Style</th><th>Rating</th>
      </thead>
      <tbody>
        <% brewery.beers.each do |beer| %>
          <tr>
              <td><%= beer.name %></td>
              <td><%= beer.style.name %></td>
              <td><%= round(beer.average_rating) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

  <% if brewery.ratings? %>
    Brewery has average of: <%= brewery.average_rating %>
  <% else %>
    Brewery has not yet been rated!
  <% end %>
  
  <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-primary" %>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit "Create brewery", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<p>Number of breweries: <%= @active_breweries.count + @retired_breweries.count %></p>

<% cache "brewerylist", skip_digest: true do %>
  <div id="active_breweries">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Founded</th>
          <th>Beers</th>
          <th>Rating</th>
        </tr>
      </thead>
      <tbody>
        <% @active_breweries.each do |brewery| %>
          <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td><%= brewery.beers.count %></td>
            <td><%= round(brewery.average_rating) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div id="retired_breweries">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Founded</th>
          <th>Beers</th>
          <th>Rating</th>
        </tr>
      </thead>
      <tbody>
        <% @retired_breweries.each do |brewery| %>
          <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td><%= brewery.beers.count %></td>
            <td><%= round(brewery.average_rating) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= link_to "List of beers", beers_path %><br/>
<%= link_to "New brewery", new_brewery_path if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>
<table id="brewerytable" class="table table-hover">
  <thead>
    <tr>
      <th> <span id="breweryName">Name</span> </th>
      <th> <span id="breweryYear">Year</span> </th>
      <th> <span id="breweryBeerCount">Beer count</span> </th>
      <th> <span id="breweryActive">Active/Retired</span> </th>
    </tr>
  <thead>
  <tbody>
    <div id="brewerieslist"></div>
  </tbody>
</table>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/panimot.html.erb
 panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<%= render @brewery %>

<div>
  <%= link_to "Edit this brewery", edit_brewery_path(@brewery) if current_user %>
  <%= link_to "Back to breweries", breweries_path %>

  <%= button_to "Destroy this brewery", @brewery, method: :delete if current_user %>
</div>